### ISSUE TITLE
Missing ./src/*.py files in 07_Dynamic_Data_Structures_Slides

### ISSUE THREAD

**Issue by magetron** [mhandley/ENGF0002#2]
Dear Prof. Handley,

When building 07_Dynamic_Data_Structures_Slides.pdf, pytest reported unable to found ./src/*.py files.
As I have checked, Python source codes are missing for this lecture and therefore no .py files can be displayed in the manual build pdf file.

Would you please upload the python files related with 07_Dynamic_Data_Structures_Slides?

Thank you in advance for your help!

Patrick

**Comment by mhandley** [comment]
Thanks - pushed now.
